name: MCJikaiPlugin
main: ovh.triedge.mc.plugin.v3.MCJikaiPlugin
version: 1.19
author: Jikai
api-version: 1.19

commands:
  warp:
    description: Manipule les teleporteurs
    usage: /warp create|remove TP_NAME
  detector:
    description: Detecte les metaux
    usage: /detector
  learsnowball:
    description: Clear toutes les snowballs sur la map
    usage: /clearsnowball